### ISSUE TITLE
"Test Results" panel aggressively steals focus 

### ISSUE THREAD

**Issue by andrewheumann** [jest-community/vscode-jest#1111]
### Environment

1. `vscode-jest version`: `6.2.0`
2. `node -v`: `v20.9.0`
3. `npm -v` or `yarn --version`: `v10.1.0`
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 
```
pringle@0.0.0 /Users/andrewheumann/Dev/pringle
├─┬ @vue/vue3-jest@29.2.6
│ └── jest@29.7.0 deduped
├── jest@29.7.0
└─┬ ts-jest@29.1.2
  └── jest@29.7.0 deduped
```
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? n/a
    - jest.autoRun? n/a
    - anything else that you think might be relevant? n/a
6. Operating system: Mac OS 14.2.1 (23C71)

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `npm run test`

### Steps to Reproduce

Example Repo https://github.com/andrewheumann/jest-steals-focus

In this bare repository, on every file save, "Test Results" steals focus in the VS code panel. I want my terminal to stay front and center. 

https://github.com/jest-community/vscode-jest/assets/31935763/fadb9b25-25e5-4e01-bd5d-eac31978b37e

In another repo, it's stealing focus on every git action.

Even if I explicitly close the `Test Results` panel tab, it re-opens itself on every file save or git action.

**Comment by connectdotz** [comment]
Hmm... This is due to the combination of the watch mode and the default TEST RESULT panel setting... 

There are (at least) 3 possible ways to change this, depending on your preference:
1. permanently change the runMode, such as: ` "jest.runMode":"on-demand"`. => If you prefer not to run tests automatically by watchman. 
2. temporarily toggle the runMode through the TestExplorer panel. => If you prefer to keep watch mode on by default and only turn it off when not needed.
3. disable the test-results panel from auto-stealing focus: `"testing.openTesting": "neverOpen"`. => This will stop the test-results panel from auto-changing focus, even when running tests. Note that you can always manually click on the panel to focus.

Let me know what you think.

**Comment by hugoburguete** [comment]
I also noticed this upon updating VSCode to the most recent release.

Option 3 seems to make the most sense to me (from a user perspective). The option of whether to run it automatically or not shouldn't be linked to focusing the test results panel.

But happy with whatever decision the maintainers choose in the end.

**Comment by connectdotz** [comment]
It seems the real issue is not the test results panel gaining focus, but rather that it captures focus **unexpectedly** or **undesirably**. Let me explain...

In scenarios like an "on-demand" runMode, where tests are initiated explicitly by the user, the automatic appearance of the test results panel might be expected and seen as beneficial by some. Similarly, in watch mode, the panel automatically grabbing focus could serve as a useful alert when code changes break tests.

This highlights that users may have varying expectations and preferences. That's why we've made these settings customizable and provided multiple [options](https://github.com/jest-community/vscode-jest/issues/1111#issuecomment-1939656073) to address this issue, so you can tailor the extension to your preferences.

However, I'm definitely open to suggestions and would love to hear if there's a more balanced approach we could consider. Your input is invaluable as we aim to improve this feature.

**Comment by connectdotz** [comment]
It looks like I have made the issue more complicated than it is, sorry. I updated my earlier [comment](https://github.com/jest-community/vscode-jest/issues/1111#issuecomment-1939656073) and provided a more straightforward answer there instead.

Please let me know if there are any other questions.

**Comment by v-msft** [comment]
It's so annoying I have multiple instances of vscode running, I can't code when Test Results are running in some instance (which are auto run btw).

**Comment by connectdotz** [comment]
@v-msft does setting `"testing.openTesting": "neverOpen"` not working for you?

**Comment by sh-pq** [comment]
I confirm that using `"testing.openTesting": "neverOpen"` for me resolves this issue.

Just this past week after updating VS Code I also noticed this issue: every single time I ran any test (such as on any save) the terminal panel would open and the Testing tab would steal focus. That was new and unpleasant, such that I had to disable the automatic test runner completely.

Using `"testing.openTesting": "neverOpen"` however just makes the tests run silently in the background which is exactly the behaviour I want.

**Comment by connectdotz** [comment]
Close this issue as there is a clear configuration solution.

**Comment by hugoburguete** [comment]
> I tried setting it to `"testing.openTesting": "openOnTestFailure"` and it still opens every time, instead of only on failures

I feel like this is a different bug from the original one. Maybe this should be raised as a different bug to mention that the setting is not working as expected?

**Comment by diyorbek** [comment]
I am still experiencing this behavior with these settings.

![Screenshot 2024-02-20 at 18 43 12](https://github.com/jest-community/vscode-jest/assets/29589560/89f0263c-4e58-4bba-9d63-7b081d646067)

**Comment by connectdotz** [comment]
@GeorgeWL I was able to repo your issue, but I think @hugoburguete is right, this is a different issue, it's actually a real bug. 😓 I will patch it shortly if you want to creat a new issue for it.

**Comment by GeorgeWL** [comment]
> @GeorgeWL I was able to repo your issue, but I think @hugoburguete is right, this is a different issue, it's actually a real bug. 😓 I will patch it shortly if you want to creat a new issue for it.

I've done that now and referenced my earlier comment in that report
