### ISSUE TITLE
[BUG] vscode-jest not  waiting for environment variable resolution

### ISSUE THREAD

**Issue by alexrecuenco** [jest-community/vscode-jest#1125]
**Describe the bug**
If I start vscode by opening a window (macOS) vscode-jest executes instantly, before waiting for environment variables to resolve.

When that happens it returns 

```
vscode jest [warn] possible process env issue detected, restarting with a login-shell...

```

And it tries to use /bin/bash as a backup (Even though /bin/zsh is my default terminal

**To Reproduce**
1. Set `"application.shellEnvironmentResolutionTimeout": 120`
2. Write in your login shell script (.zshrc/ .bashrc/ etc) `sleep 2`
3. Open a new window (not by running `code .` but by opening a workspace with code, I tried in my case with double clicking a `.code-workspace` file
4. See error above

5. Close that window
6. Open a new window with `code .`
7. The error is no longer happening.

**Expected behavior**
vscode-jest should wait for shell environment resolution before it tries to run, this extension starts faster than any other, and maybe too fast

If you use

**Screenshots**

- macOS 

```
❯ nvm --version
0.39.5
❯ node -v
v18.18.0

VERSION
        "jest": "^29.6.2",


settings.json
    "jest.jestCommandLine": "npm test -- ",
    "jest.runMode": {
        "type": "on-demand",
    },
```

**Prerequisite**
- are you able to run jest from the command line? 
-  YES
- where do you run jest CLI from? 
- YES root `npm test`
- how do you run your tests from the command line? 
- Same way

**Additional context**

If you start a new window with `code .` it works, since environment resolution happens before you open the window

---

**Comment by connectdotz** [comment]
@alexrecuenco, do you happen to have `"jest.shell"` defined? Otherwise, it will default to 'bash' when trying to run a login-shell as you have discovered.

I guess we could enhance the extension to read vscode setting for the shell used by the terminal... but let's first make sure the `"jest.shell"` works for your use case.

Regarding activating too early. It's not clear to me that there is a way to "wait" until the shell is fully initialized, as far as I know. The solution is usually just to start a "login shell" so the spawned jest process can initialize the env itself without relying on the parent process's env (vscode).

**Comment by alexrecuenco** [comment]
I am sorry, I am having a hard time reproducing this issue on the newest update. I am not sure if it was resolved, or it is something about the workspace I am using is loading jest differently now.

**Comment by connectdotz** [comment]
that's all right. I am going to close it for now. Feel free to re-open it If you experience the same problem again and setting `jest.shell` did not work.
