### ISSUE TITLE
[BUG] The plugin opens multiple terminals on startup

### ISSUE THREAD

**Issue by akrolasik-bc** [jest-community/vscode-jest#1140]
The plugin opens multiple terminals on startup.

Reproduction steps:
Open VS Code with the Jest plugin installed.

Expected behavior:
The plugin should not open multiple terminals at VS Code startup.

I use the Monorepo Workspace Plugin, which might be related.

![image](https://github.com/jest-community/vscode-jest/assets/144027475/9f6afa19-90e8-4032-b8b4-57b1196b5388)

![image](https://github.com/jest-community/vscode-jest/assets/144027475/1b013040-8c89-451a-a748-5f2e9feca9c0)

**Comment by connectdotz** [comment]
@akrolasik-bc, I didn't see your current vscode-jest configuration in the ticket, I am assuming you don't have any custom settings yet. In that case each monorepo project will be defaulting to the "watch" mode, which launches a jest process and opens the a jest terminal upon starting up, as you showed above.

You can easily customize the behavior by setting [jest.runMode](https://github.com/jest-community/vscode-jest#runmode) to "on-demand" in your settings.json or .code-workspace file: 
```json
"jest.runMode": "on-demand"
```
If you need to customize the extension further to fit your project, the [Getting Started](https://github.com/jest-community/vscode-jest#getting-started) section might be a good place to start. Please let me know if you have any other questions.

**Comment by akrolasik-bc** [comment]
Hello!

Reproduction Steps:
1. Closed all terminals.
2. Set "jest.runMode": "on-demand".
3. Reopened VS Code.
4. Terminals for all the projects opened again.

Expected Behavior:
The plugin should not open multiple terminals at VS Code startup.
In fact it should not open any terminal on startup by default.
Please do not overwhelm the IDE with your plugin.

Thank you.

**Comment by akrolasik-bc** [comment]
Also, I hid most of the project in the Test Explorer, but now all the projects are visible again. This is overwhelming too.

**Comment by connectdotz** [comment]
@akrolasik-bc, did the terminal show jest run command and output (scroll to the end)? I suspect the "jest.runMode" didn't take effect somehow... When you said, "hid most of the projects in the Test Explorer," did you mean "collapsing"? 

It will be most efficient if you have a sample repo so we can take a look at why "jest.runMode" didn't work for your project. Otherwise, please provide more information on your project structure, such as if you have a multi-root workspace? Did you setup your project following the [monorepo setup](https://github.com/jest-community/vscode-jest?tab=readme-ov-file#how-to-use-the-extension-with-monorepo-projects) instruction in the README? Where did you put the "jest.runMode" setting etc...

**Comment by connectdotz** [comment]
> The plugin should not open multiple terminals at VS Code startup.
> In fact it should not open any terminal on startup by default.
> Please do not overwhelm the IDE with your plugin.

I can see that the default "watch" mode could be overwhelming for large monorepo projects, whereas simpler projects might appreciate its automaticity. We are indeed considering changing this default; your use case provides a useful data point. Thanks.

**Comment by akrolasik-bc** [comment]
Hello! The deferred setting corrected the behavior. Thank you!

I have one directory containing multiple projects. In the main directory, I have a file with the extension .code-monorepo that works with the Monorepo Workspace extension. I have configured multiple virtual folders in the monorepo file. I placed the "jest.runMode" setting alongside all my other settings in the "settings" section of my .code-workspace file.

**Comment by connectdotz** [comment]
@akrolasik-bc, I'm glad you were able to resolve this issue using the "deferred" mode. This confirms that the `"jest.runMode"` setting has been successfully applied.

I will close this issue since the setting is working as expected. As mentioned earlier, we are considering changing the default `"jest.runMode"`. Thank you for bringing this issue to our attention.
