### ISSUE TITLE
[BUG] Invalid test path pattern generated when running a test on windows

### ISSUE THREAD

**Issue by Tiberriver256** [jest-community/vscode-jest#1163]
**Describe the bug**
When I attempt to run a single test it generates an invalid pattern if the filename has any period in it.

For example, if I have a file located at `C:\my-project\src\mytest.test.tsx`

The following pattern is generated:
`C:\my-project\src\mytest\.test\.tsx`

The following should be generated:
`C:\my-project\src\mytest.test.tsx`

**NOTE: Debugging a single test generates a valid `testPathPattern` it is only when I run a single test that I have this problem.

**To Reproduce**
1. Go to a file containing tests
2. Right click on the icon in the side-bar
3. Click `Run Test`
5. See error

**Expected behavior**
It should run the test

**Screenshots**
![image](https://github.com/user-attachments/assets/80dc5129-39bf-4b00-b742-b67ffa91b8cb)

**Environment (please complete the following information):**
- vscode-jest version: 6.2.5
- `node -v`: 20.8.0
- `npm -v` or `yarn --version`: 10.1.0
- jest or react-scripts (if you haven’t ejected) version: 27.5.2
- Operating system: Windows 11

**Prerequisite**
- are you able to run jest from the command line? yes
- where do you run jest CLI from? Root of project
- how do you run your tests from the command line? npm run test

**Comment by connectdotz** [comment]
@Tiberriver256

This issue is a bit puzzling... Since all test files have dot separators, this should normally work with this extension. It seems possible that something specific in your environment might be causing the regex escape pattern to be interpreted differently.

If you could provide a sample repo, it would help us investigate further. If that's not possible, could you please provide some additional information?

1. Do you have any custom configurations, such as `jest.jestCommandLine`?
2. If you have a customized debug configuration (in your `.vscode/launch.json`), could you share it with us?
3. Could you also show us the command that was spawned, as seen in the console.log? For reference, you can check [How to see more debug info (self-diagnosis)](https://github.com/jest-community/vscode-jest?tab=readme-ov-file#how-to-see-more-debug-info-self-diagnosis).

Thanks!

**Comment by Tiberriver256** [comment]
I didn't have any custom commands.. but ended up upgrading to jest 29 for something unrelated and that seems to have fixed it 🤷‍♂️
