### ISSUE TITLE
Provide Option to Specify `testRegex` or `testMatch` in VsCode Settings

### ISSUE THREAD

**Issue by duffbuster** [jest-community/vscode-jest#224]
I would like to use this extension with TypeScript, but am not able to change the default test regex for finding test files. I suggest adding a VsCode settings option to override the default value to allow for `.ts` and `.tsx` files if needed.

**Comment by seanpoulter** [comment]
Sorry to hear you're having problems @duffbuster. Where have you tried changing the test regex, and does it work from the console?
<br/>

If you've changed the Jest configuration in `package.json` or `jest.config.js` Jest should pick up those changes. If you're using a non-standard filename like `jest.json`, you can use the `"jest.pathToConfig"` setting to set the value of the `jest --config` argument.

When the extension loads, the settings are parsed. It's possible that you may need to reload the window for the extension to recognize changes to the settings.
<br/>

As for your feature request for a setting, we'd love your help looking into it. It seems like it might be a bit of a challenge since Jest doesn't seem to have a CLI option [in the docs](https://facebook.github.io/jest/docs/en/cli.html) to change the `testMatch`.

**Comment by duffbuster** [comment]
@seanpoulter turns out I was setting the `jest.pathToConfig` value incorrectly. I fixed it and the extension works perfectly! Thanks for the tip!

**Comment by seanpoulter** [comment]
Happy to hear it's working. :+1:
