### ISSUE TITLE
Wrap inline error messages

### ISSUE THREAD

**Issue by garyking** [jest-community/vscode-jest#309]
Is it possible to wrap inline error messages? Since they are added as comments at the end of lines, they almost always require scrolling horizontally.

**Comment by seanpoulter** [comment]
We've got an open issue with a request to wrap the inline error messages but based on how old it is I don't think we've checked if it's possible in VS Code now. Would you be willing to have a look at the VS Code docs to see if it's possible @garyking?

I'm going to close this issue since #133 is still open.
