### ISSUE TITLE
Custom Css ext doesnt seem to work

### ISSUE THREAD

**Issue by pshort** [jest-community/vscode-jest#314]
### Environment

1. `node -v`: 8.4.0
2. `npm -v`: 5.3.0
3. `npm ls react-scripts` (if you haven’t ejected): [fill]

4. Operating system: WIndows 10

### Steps to Reproduce

I install the ext in vs code. I reload. I get a dialog saying i need to run in admin mode to make changes (from custom css extension). I run in admin mode. I try to enable custom css + js. I get corrupted error. I ignore as per custom css ext instructions. I get "admin mode required" dialog again.

### Expected Behavior

Extension installs and works

### Actual Behavior

Jest runner works but output in window looks horrible. Probably the css extension blowing up

--- 

Note we are looking for someone to take responsibility around keeping create-react-app up to date and working, could this be you?

**Comment by seanpoulter** [comment]
Thanks for taking the time to report an issue @pshort. Unfortunately I can't help you without more information. The problem you're describing sounds like it's coming from your third-party CSS extension. If you disable the CSS extension, reload the window, and Jest is working OK without the errors then you've confirmed it's an issue with the CSS extension (or a conflict).

If you think this is a legitimate problem, please re-open the issue and provide all the details someone would need to recreate the error(s). A repo with the minimal amount of code to reproduce the problem is appreciated.

For what it's worth, I've been working with the extension since the Fall and haven't been prompted to run in Admin mode.

Good luck!
