### ISSUE TITLE
How to change jest config in CRA?

### ISSUE THREAD

**Issue by dimitri-a** [jest-community/vscode-jest#392]
When using create-react-app how can I change the jest configuration without ejecting the app? How can I specify a different location for files instead of the default one?

**Comment by stephtr** [comment]
In principle it should be possible to add a custom jest.config.js and refer to that in this plugin's settings. However I would strongly recommend against that method and stick with the already included Jest configuration. A few parameters can be changed by adding them to the test command in your package.json, but probably not the locations.
Since your question is not really related to this plugin and we are not experts with creact-react-app, I will close the issue. Your question is probably in better hands on StackOverflow or create-react-app's repository.
