### ISSUE TITLE
Upgrade to VS Code's webview API 

### ISSUE THREAD

**Issue by mjbvz** [jest-community/vscode-jest#403]
Hi, I'm on the VS Code team. I noticed that your extension uses the `vscode.previewHtml` command which is deprecated and which we are actively working to remove: https://github.com/Microsoft/vscode/issues/62630

We've developed a [webview API][docs] that provides a much better developer experience and offers a number of important security and compatibility benefits over `previewHtml`. We cannot fix `previewHtml` without breaking backwards compatibility, and have instead opted to remove it. 

To ensure that your extension continues to work properly in VS Code, please try upgrading to use the new Webview API. You can find documentation on the API usage [here][docs]. Let me know if you have any questions or concerns about this migration

[docs]: https://code.visualstudio.com/docs/extensions/webview

**Comment by seanpoulter** [comment]
Thanks for the heads up @mjbvz.

What do you have in mind for Gitter @nasreddineskandrani? If you're joking that you rely on this extension for your business, I'm happy to help review your PR.

**Comment by nasreddineskandrani** [comment]
a gitter channel. It may be helpful for you extension. 
People can ask live question. For example the overlay for the coverage is not working. It's more easy to live chat about this kind of issues. Maybe some devs has an old version where it's working or maybe it's due to a new version of vscode and some people can tell us which version is fine etc...
since it's free why not? some great lib use gitter as angular or ngrx and it's helpfull.

**Comment by mjbvz** [comment]
Just a heads up: in VS Code 1.32 (the February update), using the previewHtml command will show an alert to the user, although the command should still work. We plan to remove the command entirely with VS Code 1.33 (March update)

**Comment by dons20** [comment]
The March update is probably coming soon, any update on this?
