### ISSUE TITLE
Coverage Overlay not highlighting the same as coverage/index.html

### ISSUE THREAD

**Issue by nasreddineskandrani** [jest-community/vscode-jest#411]
### Environment
`node -v`:  v8.11.3
`npm -v`: 5.6.0
Operating system: windows10

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line?
```
yarn run testjest:watch --coverage --runTestsByPath src/app/game/game-a.service.spec.ts
```

### Steps to Reproduce

a sample repo branch with the problem
https://github.com/nasreddineskandrani/full-example-angular/tree/jest-playaround

commands:

> yarn install
> yarn run testjest:watch -- --coverage

 for the same test run if i remove the test in my spec file for the `false` branch in game-a.service.spec.ts

1.
**index.html coverage:**
![image](https://user-images.githubusercontent.com/1953635/49355813-42710d80-f697-11e8-86a5-198bc6aae3ff.png)

2.
**overlay coverage:**
![image](https://user-images.githubusercontent.com/1953635/49355848-60d70900-f697-11e8-95fc-1b403bfe1531.png)

--------------------
you can see that the `true` branch is still highlighed by the overlay in vscode => when `index.html` coverage is not highlihgting this branch.

### Relevant Debug Info

i did not debug it yet.

### Expected Behavior

coverage/index.html and coverage overlay in vscode are the same

### Actual Behavior
covergae/index.html and coverage overlay in vscode are NOT the same

**Comment by markcarroll** [comment]
I'm seeing the same thing, where branches are highlighted as not covered in vscode-jest but are showing as covered in the `index.html` test report as verified by stepping through my test code in the debugger.

**Comment by fabis94** [comment]
experiencing the same thing

**Comment by AverageHelper** [comment]
Same here.

**Comment by connectdotz** [comment]
Hi, I looked at the sample repo today, and looks like the `index.html` does show the branch is NOT covered, just that it used the `E` marker instead of red block, you can also see the top summary showed 60% branches coverage to confirm that...

Is this issue about the uncovered branch should be marked differently or you think the branch should be covered? If it is about the later, then the issue is probably within jest or Istanbul library that jest used to generate the coverage report...

**Comment by nasreddineskandrani** [comment]
@connectdotz what do you mean? you can do exactly what is done in index.html this is the standard for most testing coverage tools...

**Comment by connectdotz** [comment]
@nasreddineskandrani in your sample repo, you have tested the `if` path by evaluating 
```
expect(gameAService.play(heroes)).toEqual(true);
```
but you didn't evaluate the hidden `else` path, which should returns `false`. Therefore you have only partially tested your branch. The `E` marker in the index.html means missing coverage on `Else` path; it will put a marker `I` for missing `If`path, you can play with it to see that effect. 

> you can do exactly what is done in index.html this is the standard for most testing coverage tools it's highlighted in red when not covered

Just to be sure, the index.html (Istanbul report) is telling you the branch is not fully covered, it just didn't use the red marker but the `E`. Actually there are many more types of "missing coverage" the report uses: [How do I rea an Istanbul Coverage Report?](https://stackoverflow.com/questions/26618243/how-do-i-read-an-istanbul-coverage-report).

I think your suggestion to adopt the same report scheme is good, we can certainly use the same color scheme, provided they look right in vscode editor (lite/dark mode). However, we probably won't use the `E` or `I` marker, as they will interfere with code formating since we are dealing with text editors here, unlink the report is a read-only HTML page... That is why I am thinking of using different colors to represent them, I am all ears if you have other suggestions...
