### ISSUE TITLE
Coverage live update

### ISSUE THREAD

**Issue by armoucar** [jest-community/vscode-jest#559]
Coverage works when I start vscode, then if I make the test pass, it'll clean up the red background in the covered lines, but if I uncover them again, the red lines won't appear again.

**Comment by seanpoulter** [comment]
Thanks for opening the issue @armoucar. This makes me sad.

How would you and the other folks feel about trying to fix it? We'd be happy to review a PR. We'd also be happy to have some help reviewing PRs. 🙈

I'll admit, it has been a while since I've worked on this but the [Contributing](https://github.com/jest-community/vscode-jest/blob/master/CONTRIBUTING.md#how-to-contribute) docs should get you started.
