### ISSUE TITLE
Is there any way to make this extension run tests with runInBand parameter?

### ISSUE THREAD

**Issue by da1z** [jest-community/vscode-jest#565]

**Comment by pmcelhaney** [comment]
In settings.json:

```json
 "jest.pathToJest": "./node_modules/.bin/jest --runInBand"
 ```

**Comment by sadeghhosseini** [comment]
`jest.pathToJest` is deprecated in new versions, and you have to set `jest.jestCommandLine`, in order to do that you can go to the settings panel for the extension (by searching the extension in the "search extension" in vscode and clicking on the gear icon on the extension and selecting "Extension Settings" from the opened list), and as shown in the following image you can set  the value for `Jest: Jest Command Line` to `"./node_modules/.bin/jest" --runInBand`.

You can update the `settings.json` manually too, all you have to do is adding the following line to the `settings.json`
```json
"jest.jestCommandLine": "\"./node_modules/.bin/jest\" --runInBand"
```


*note* in windows I had to wrap `./node_modules/.bin/jest` in double quotes(as I have in the preceding examples), otherwise it did not work.


![image](https://user-images.githubusercontent.com/13155024/170934567-e1b5383a-f912-4c30-bc43-569bdc344dbc.png)

**Comment by connectdotz** [comment]
this should have been closed after v4 release. Yes you can use `jest.jestCommandLine` to pass with any valid jest argument.
