### ISSUE TITLE
extension doesn't activate on remote hosts

### ISSUE THREAD

**Issue by fiksen99** [jest-community/vscode-jest#711]
### Environment

1. `vscode-jest version`: 4.0.1
2. `node -v`: local: 15.2.0, remote: 10.23.1 
3. `npm -v` or `yarn --version`: 1.17.0-20190429.1820
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): unable to run `npm` on locked down machine
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? N/A
    - jest.autoRun? 
    ```
    {
        "watch": true,
        "onStartup": [
            "all-tests"
        ]
    }
    ```
    - anything else that you think might be relevant? I'm connected to a [remote server](https://code.visualstudio.com/docs/remote/remote-overview) where I'm developing from. We also have a custom fork of VS Code, so it may be something internal to us if this doesn't repro on vanilla VS Code
6. Operating system: local: Mac OSX Big Sur, remote: CentOS v9

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `yarn utest {regexToTest}`

### Steps to Reproduce

Open any valid js repo, however have it located in a remote server and use VS Code Remote Development to connect to it. Mount the root of the project.

### Relevant Debug Info

None - the extension doesn't activate

### Expected Behavior
 The extension activates

### Actual Behavior

It doesn't

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
hi, this extension has the following activation events:
```
"activationEvents": [
    "workspaceContains:jest.config.js",
    "workspaceContains:jest.json",
    "workspaceContains:node_modules/.bin/jest",
    "workspaceContains:node_modules/react-scripts/node_modules/.bin/jest",
    "workspaceContains:node_modules/react-native-scripts",
    "onCommand:io.orta.jest.start"
  ],
```
does any of that apply in your use case?

**Comment by fiksen99** [comment]
from the mounted folder I see: 

```
> find . -name "jest"

./node_modules/@types/jest
./node_modules/jest
./node_modules/jest/node_modules/.bin/jest
./node_modules/jest-mock-extended/node_modules/.bin/jest
./node_modules/.bin/jest
```

None of these match exactly the string, however this same file pattern is found on my locally hosted codebase where the extension does activate.

On my remote host, I tried creating a file `jest.json` in the root of the mounted folder, just to try to force the activation. Closed and reopened vs code at the same mounted folder but still didn't activate.

**Comment by connectdotz** [comment]
> None of these match exactly the string,

actually, the last one `./node_modules/.bin/jest` would match.

is there any error message in OUTPUT channel or Developer Console (Help > Developer Tools)? Are you able to manually start the extension by running the `Jest: Start All Runner` via command palette?

**Comment by adun** [comment]
### Environment

1. `vscode-jest version`: [4.2.1]
2. `node -v`: [16.14.0]
3. `npm -v` or `yarn --version`: [8.3.1]
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected):
[jest-vscode-remote-container@1.0.0 /workspaces/jest-vscode-remote-container
└── jest@27.5.1]
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [npx jest]
    - jest.autoRun? [{ "watch": true, "onStartup": ["all-tests"], }]
    - anything else that you think might be relevant? [Extension hbenl.vscode-test-explorer is installed]
6. Operating system: [Windows11 + WSL2]

### Prerequisite
- are you able to run jest test from the command line? [yes]
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) [npx jest] 
  (npm run test works in command line but doesn't work in the devcontainer setting : *"jest.jestCommandLine": "npm run test"*)

### Steps to Reproduce

Here is the sample repo [jest-vscode-remote-container](https://github.com/adun/jest-vscode-remote-container) with a working use case. 

### Expected Behavior

Run jest tests on container build and file save

### Actual Behavior

Run jest test only on container build

---

Hello, 

I'm also trying to make Jest extension to work in a remote container. This issue is quite old but still open so I'm adding my findings here. 
I've managed to make the extension run tests on container startup, however watching file changes in files doesn't work. 

Running the command: **Jest: Start All Runners** will re-runs all tests in my project. 

I've made the following changes in my devcontainer config file:

`devcontainer.json - without launch options`
```
  // Set *default* container specific settings.json values on container create.
  "settings": {
    "jest.jestCommandLine": "npx jest",
    "jest.autoRun": {
      "watch": true,
      "onStartup": ["all-tests"],
    }
  },
```

`devcontainer.json - with launch options`
```
  // Set *default* container specific settings.json values on container create.
  "settings": {
    "launch": {
      "configurations": [
        {
          "type": "node",
          "name": "vscode-jest-tests",
          "request": "launch",
          "args": ["--runInBrand", "--watchAll=false"],
          "cwd": "${workspaceFolder}",
          "console": "integratedTerminal",
          "internalConsoleOptions": "neverOpen",
          "program": "${workspaceFolder}/node_modules/.bin/jest",
          "windows": {
            "program": "${workspaceFolder}/node_modules/jest/bin/jest"
          }
        }
      ]
    },
    "jest.jestCommandLine": "npx jest",
    "jest.autoRun": {
      "watch": true,
      "onStartup": ["all-tests"]
    }
  },
```

Thanks
adun~
