### ISSUE TITLE
Jest extension sets environment variable CI to true

### ISSUE THREAD

**Issue by HarisaranG** [jest-community/vscode-jest#723]
### Environment

1. `vscode-jest version`: [fill]
2. `node -v`: [fill]
3. `npm -v` or `yarn --version`: [fill]
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [fill]
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [fill]
    - jest.autoRun? [fill]
    - anything else that you think might be relevant? [fill]
6. Operating system: [fill]

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) yes

### Steps to Reproduce

[fill]

### Expected Behavior
CI should be false

### Actual Behavior
CI is expected to be true

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by TheAlmightyBob** [comment]
Is this causing an actual problem? At one point this led to a conflict with `vscode-react-native`, but they looked into it and found that `jest-editor-support` is actually the thing adding `CI`, and it seemed necessary, so they made the fix in `vscode-react-native` instead. See: https://github.com/microsoft/vscode-react-native/issues/1529#issuecomment-801810946

(so if this _is_ causing a problem, you probably want to file an issue with `jest-editor-support` instead of `vscode-jest`)

**Comment by HarisaranG** [comment]
I found a workaround to fix this.
In my VS Code settings, I added
`"jest.jestCommandLine": "CI=false && npm test"`,

Anyways, Thanks for the reply
