### ISSUE TITLE
Test involving Spinner passes in terminal, but fails in extension

### ISSUE THREAD

**Issue by lachiejames** [jest-community/vscode-jest#732]
### Environment

1. `vscode-jest version`: 4.0.3
2. `node -v`: 12.18.2
3. `npm -v` or `yarn --version`: 6.14.5
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 27.0.4
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [fill]
    - jest.autoRun? [fill]
    - anything else that you think might be relevant? [fill]
6. Operating system: Windows 10

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) jest

### Steps to Reproduce

1. Clone https://github.com/lachiejames/jest-bug
2. Install dependencies using `npm install`
3. Enable `vscode-jest` extension in VScode
4. Run test from command line using `jest`, which will **pass**
5. Run test using `vscode-jest` extension, which will **fail**

### Expected Behavior

```
it("jest bug",()=>{
    const oraInstance:Ora = ora();
    expect(oraInstance.isSpinning).toEqual(false)
    oraInstance.start("test")
    expect(oraInstance.isSpinning).toEqual(true)
    oraInstance.stopAndPersist()
})
```
should pass when using the `vscode-jest` extension

### Actual Behavior

```
it("jest bug",()=>{
    const oraInstance:Ora = ora();
    expect(oraInstance.isSpinning).toEqual(false)
    oraInstance.start("test")
    expect(oraInstance.isSpinning).toEqual(true) <-- this line fails when using the `vscode-jest` extension
    oraInstance.stopAndPersist()
})
```

![image](https://user-images.githubusercontent.com/47808687/122764697-16641900-d2e3-11eb-885c-d10957f7d029.png)

![image](https://user-images.githubusercontent.com/47808687/122764939-55926a00-d2e3-11eb-87ff-1f71d5eafbee.png)

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
thanks for the repo, I played with it and found the culprit is the `--watch`or `--watchAll` flag. The default behavior for the extension is to run jest in watch mode, i.e. with `--watch` flag, somehow with the flag the test failed. You can reproduce this behavior outside of the extension, for example, execute  `yarn test --watchAll` in the terminal. Therefore don't think the issue is related to the extension...

Not sure why the test fails in watch mode, you can try to resolve the root cause outside of the vscode-jest, or customize vscode-jest to work around it by not using watch mode, see document on [autoRun](https://github.com/jest-community/vscode-jest#how-to-trigger-the-test-run) (expand the arrows).

Feel free to reopn the issue if you still have problems.
