### ISSUE TITLE
Add inline button to run test

### ISSUE THREAD

**Issue by Igorgro** [jest-community/vscode-jest#760]
Inspired by #509. Deno extension add inline button to run every test separately:
![изображение](https://user-images.githubusercontent.com/22894169/131029092-e8c5c179-8635-48c2-87c7-ed09993cc6f6.png)
I think the same functionality can be implemented in this extension.

**Comment by connectdotz** [comment]
with test explore status icon, one can run/debug individual tests pretty easily now, as long as it is under "interactive" mode:

![run-test](https://user-images.githubusercontent.com/891093/131281710-a66dba15-6202-421e-aa3e-2bd5d656baf0.gif)

**Comment by Igorgro** [comment]
The problem is the same as in the issue i mentioned. What if I has a project with a lot of tests and don't want to run jest in watch mode?

**Comment by connectdotz** [comment]
> What if I have a project with a lot of tests and don't want to run jest in watch mode?

I assume you are referring to the interactive mode use case when no test is run and the test explorer/status is empty? It's true in that case you will not be able to run individual tests, but you can easily trigger the file-based test via the context menu ["Jest: Run Related Tests"](https://github.com/jest-community/vscode-jest/issues/509#issuecomment-860314721), which should just run that given test file, not the whole project. After the tests are executed and posted in the explorer, you can then run individual tests via the mechanism mentioned above...

**Comment by Igorgro** [comment]
Yes, this is another good option, but the feature I asked in the first comment is about running one specific test (or group of tests) instead of running all test for the whole file

**Comment by SenseiMarv** [comment]
I recently switched from the Test Explorer UI extension to the official Testing Explorer and in the Jest Test Adapter there (https://marketplace.visualstudio.com/items?itemName=kavod-io.vscode-jest-test-adapter) there were 3 options in the code lens: `Run`, `Debug`, `Reveal in Test Explorer`. I would like to see this extension adapt this behaviour. In my eyes it is more consistent to have `Run` and `Reveal in Test Explorer` in addition to `Debug` in the code lens.

**Comment by connectdotz** [comment]
Adding additional codeLens is trivial, however giving the fact that these hooks already exist in the official test-explorer status menu (see gif [above](https://github.com/jest-community/vscode-jest/issues/760#issuecomment-907988727)), it didn't feel right to duplicate...

I am thinking the main problem of using the status menu vs codeLens is due to the interactive mode did not populate the test explorer status until at least one test run (and plus maybe the status menu is not a well-known UI yet), while the codeLens uses a lexical parser thus can be shown before the test run... 

We could resolve this by publishing the parse result to the test explore, so any test block in the editor will have access to the status indicator and menu, regardless of the run mode. In that case, they could replace codeLens, which could sometimes interfere with code formatting and impact rendering performance... what do you guys think?

However, noted that tests discovered via lexical parser will not be able to resolve the "dynamic content", such as template literal, `test.each()` etc. In these cases, I think we could probably fall back to the file level run behind the scene...

**Comment by connectdotz** [comment]
To summarize the question: if we can make "debug", "run", "reveal" functionality for each test block available from the status menu (in the gutter) the same way codeLens do, i.e. with or without a test run, will that be sufficient to replace codeLens? If there is an argument that still prefers codeLens, please elaborate...

@stephtr @orta do you guys have an opinion?

**Comment by stephtr** [comment]
I would prefer to have the "debug" command both in the status menu and (in case the test is failing) in the code lens, since the discoverability of the latter is easier.

**Comment by connectdotz** [comment]
the status menu will always have that 3 options, regardless of the test status (success, failure etc), so they are "truly" redundant, i.e. there is no use case that one is available while the other is not... (once we publish parse result to the explorer that is).

**Comment by Igorgro** [comment]
May be I don't speaking clearly in previous comments, but I want to repeat: if watch mode is turned off (i.e `"jest.autoRun": "off"`), there is no status menu available because status icons are not shown.

**Comment by connectdotz** [comment]
@Igorgro precisely, as I mentioned in this [comment](https://github.com/jest-community/vscode-jest/issues/760#issuecomment-912856729):

> I am thinking the main problem of using the status menu vs codeLens is due to the interactive mode did not populate the test explorer status until at least one test run

Exactly as you pointed out. IMHO, that is the right problem to fix. Once we did that, i.e. the test status will always be visible, regardless of the test run status. See a snapshot of this prototype below: from the autoRun "off" project, you can see non of the tests is run, but the "arrow" status are still shown and the menu is accessible:

<img width="1111" alt="Screen Shot 2021-09-05 at 5 10 28 PM" src="https://user-images.githubusercontent.com/891093/132141568-543622b0-1662-4f44-b602-cb09e15f727d.png">

What I tried to say is once we addressed this issue, the codeLens will become truly redundant, we can remove it, eventually...

**Comment by connectdotz** [comment]
Hi just submitted the prototype #773. 

Feel free to try the `vscode-jest-4.2.0-rc.1.vsix` there and let us know if there is any issue. thanks.
