### ISSUE TITLE
Jest extension fails with `yarn: command not found`

### ISSUE THREAD

**Issue by limitedmage** [jest-community/vscode-jest#828]
### Environment

1. `vscode-jest version`: 4.2.1
2. `node -v`: 16.7.0
3. `npm -v` or `yarn --version`: 1.22.10
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 26.6.3
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? `yarn test`
    - jest.autoRun? `true`
    - anything else that you think might be relevant? [fill]
6. Operating system: macOS 12.1

### Prerequisite
- are you able to run jest test from the command line? Yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `yarn test`

### Relevant Debug Info

`yarn` works no problem on both the native  macOS terminal and the VS Code terminal tab. However, when I try to run the `Jest: Start all runners` command, it fails and I get the following output from the Jest extension:

```
not-test onProcessExit: process exit with code=127, signal=undefined
 see troubleshooting: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting
/bin/sh: yarn: command not found
Jest process "watch-tests" ended unexpectedly
 see troubleshooting: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting
```

I tried changing to zsh using `"jest.shell": "/bin/zsh"` but I get the same error (but with zsh instead of sh).

**Comment by jdmoody** [comment]
I have the same issue. Very similar setup except I'm on Node v12 and have `autoRun` set to `off`.

One thing I noticed is that in the VSCode Console's OUTPUT tab, I see two Jest processes. One titled `Jest ({nameOfMyProject})` and another titled `Jest (Workspace)`. I'm not sure what the difference between the two is, but the `({nameOfMyProject})` one has an error and the Workspace one does not.

**Comment by connectdotz** [comment]
These sounded like runtime env related issue, you can expand the `I got "Jest Process xxx failed unexpectedly..." or "Jest failed too many times..." error message` in the [troubleshooting](https://github.com/jest-community/vscode-jest#troubleshooting) section for more info, particularly check out this [comment](https://github.com/jest-community/vscode-jest/issues/741#issuecomment-921222851) for more detailed explanation and suggestions.

@jdmoody if your project is a multi-root project, then a summary output of the project `Jest (Workspace)` will be created, while the `Jest (your-project)` is for each workspace/folder.

**Comment by kumphol** [comment]
I have tried to fixed this problem so many times and spent a lot of days to fix this and I found my solution now. 

The problem is vs code workspace needs to specific jest command line but for vs code workspace itself cannot find exactly folder then before my setting in .code-workspace is

` "jest.jestCommandLine": "yarn test", `

An it showed an error like 

`/bin/sh: yarn: command not found`

Then from the setting detail on the jest project web page. I found this section.


jestCommandLine | The command line to start jest tests | undefined | "jest.jestCommandLine": "npm test -" or "jest.jestCommandLine": "yarn test" or "jest.jestCommandLine": "node_modules/.bin/jest --config custom-config.js"
-- | -- | -- | --


And I think why I don't try to specify directory and jest config by myself? then I try

` "jest.jestCommandLine": "../functions/node_modules/.bin/jest --config ../functions/jest.config.js",`

Boom ~ it's work.!!!

**Comment by zgajo** [comment]
I've resolved this issue by adding export `PATH=/opt/homebrew/bin:$PATH` to  `~/.zprofile` which gives a path to my yarn command. (I've installed yarn using homebrew)

By adding export PATH=/opt/homebrew/bin:$PATH to your .zprofile, it's ensured that this PATH modification is applied in all login shells. This is particularly important because some applications, like VS Code as I understand, may start a login shell for their integrated terminal or extensions like the Jest extension.

In contrast, if you only set the PATH in .zshrc, it would only affect interactive shells that you start manually (like opening a terminal window), but might not affect applications that start their shell environments.

**Comment by malik-samad** [comment]
I've resolved it by adding the path in the `~/.bash_profile` file,
initially, I tried to add it to `~/.zprofile` but it did work even when I configured .vscode settings to run it explicitly on **zsh** instead of **bash**.  _(by default my mac is running jest test on bash)_

Just for details on this, 
1. Open up the terminal and run `nano ~/.bash_profile`
2. Once it opens the file, past this `export PATH=/opt/homebrew/bin:$PATH` in it on an empty line.
3. Press `control + X` to initiate exit, and you will see the option to save changes, press `Y` to save it.

that's it, Hopefully, this will fix the issue for you as well.

> I've resolved this issue by adding export `PATH=/opt/homebrew/bin:$PATH` to `~/.zprofile` which gives a path to my yarn command. (I've installed yarn using homebrew)
> 
> By adding export PATH=/opt/homebrew/bin:$PATH to your .zprofile, it's ensured that this PATH modification is applied in all login shells. This is particularly important because some applications, like VS Code as I understand, may start a login shell for their integrated terminal or extensions like the Jest extension.
> 
> In contrast, if you only set the PATH in .zshrc, it would only affect interactive shells that you start manually (like opening a terminal window), but might not affect applications that start their shell environments.

**Comment by pljeskavica** [comment]
> I tried changing to zsh using `"jest.shell": "/bin/zsh"` but I get the same error (but with zsh instead of sh).

I was able to resolve this problem by making this update to my settings.json

**Comment by atl-commit** [comment]
> > I tried changing to zsh using `"jest.shell": "/bin/zsh"` but I get the same error (but with zsh instead of sh).
> 
> I was able to resolve this problem by making this update to my settings.json

Worked for me. But only _after_ restarting vscode.
