### ISSUE TITLE
vscode-jest doesn't shows in extension tab, and test files. 

### ISSUE THREAD

**Issue by dante01yoon** [jest-community/vscode-jest#853]
### Environment

1. `vscode-jest version`: [v4.4.0]
2. `node -v`: [v14.17.1]
3. `npm -v` or `yarn --version`: npm [8.5.1]
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [empty]
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [fill]
    - jest.autoRun? [fill]
    - anything else that you think might be relevant? [fill]
6. Operating system: [fill]
macos

### Prerequisite
- are you able to run jest test from the command line? [yes]
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) [npm run test]

### Expected Behavior

I have two projects using jest in my macOS, 
first project looks work well with vscode-jest, 

[
create-react-app 

![스크린샷 2022-04-24 오후 12 05 47](https://user-images.githubusercontent.com/6510430/164954636-0f6a8811-fcba-4451-8449-831b3b9ac005.png)
[fill]
]

### Actual Behavior

[
but second one is not. ( vitejs react-ts template) 
![스크린샷 2022-04-24 오후 12 06 07](https://user-images.githubusercontent.com/6510430/164954641-826a6e6d-74bd-4c5b-a564-9941e4a16eda.png)

I reloaded my vs-code several times, but  test extension icon doesn't show up.

]

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
from your screenshot, the second project's root directory seems to be one level above the actual jest config file, thus not triggering the activation events: see [activationEvents](https://github.com/jest-community/vscode-jest/blob/f380f7fc1b6d13841d4370daa7a8e5f223b941d5/package.json#L33).

If there are multiple projects/folders under the root, consider converting your workspace to vscode's [multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces), otherwise, create the vscode project in the `fontend` folder, not one above.

If none of the above worked, you might need to provide a sample project for a more detailed investigation.

**Comment by dante01yoon** [comment]
@connectdotz  thank you for responding! I'll check multi-root workspace and see what's could be changed
