### ISSUE TITLE
Unable to disable terminal on launch

### ISSUE THREAD

**Issue by kyleschaeffer** [jest-community/vscode-jest#854]
In the `4.4.0` release notes, I see this new feature highlighted:

> enhanced test output discovery by automatically opening TestExplorer terminal upon launch.

Is there an option to disable this? I personally use this extension for quick success/failure visualization in the code margins, and I switch to my terminal app (not a panel within VSCode) when I need more granular test output. I don't use VSCode terminals and I'd prefer not to have to close them every time I launch or reload the window.

Thanks for all your great work on this extension — it's invaluable!

**Comment by ixartz** [comment]
Hi @connectdotz, I have the same issue with @kyleschaeffer, I also don't want the terminal to be opened automatically. Is it possible to revert the change: https://github.com/jest-community/vscode-jest/pull/797 or add a preference to disable it?

**Comment by KevinBatdorf** [comment]
Experiencing this too. It opens on every project just to report no tests were found 🥸

**Comment by kb-ig** [comment]
I also need this disabled. Every time I open VSCode it, this terminal takes focus over my main default terminal. Quite annoying. 

I've rolled back to `4.2.1` in the meantime.

**Comment by connectdotz** [comment]
ok, I think we can add a setting to opt-out.

**Comment by connectdotz** [comment]
feel free to try the pre-release 4.5.0, you should be able to turn off the terminal with `"jest.showTerminalOnLaunch": false` setting.

**Comment by ixartz** [comment]
Thank you @connectdotz! Couldn't wait to see release in the stable version.

**Comment by kb-ig** [comment]
@connectdotz Any idea if `jest.showTerminalOnLaunch` this has been removed in later versions? I'm on `v5.1.0` now and this option is not recognised and has no effect.

**Comment by janaagaard75** [comment]
> @connectdotz Any idea if jest.showTerminalOnLaunch this has been removed in later versions? I'm on v5.1.0 now and this option is not recognised and has no effect.

Came here for the same question, and it does indeed seem to have been removed: [Breaking changes in v5](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v5.md#breaking-changes).

Why were these feature removed? Is it just temporary until v5 becomes feature complete with v4? While I do use VSCode's terminal window, it's not something that keep open, because I prefer having more screen real estate for my code, and to be less distracted.

**Comment by connectdotz** [comment]
Yes, `jest.showTerminalOnLaunch` is deprecated in v5.

In 4.6 the terminal was either open **unconditionally** or not open at all (with the `jest.showTerminalOnLaunch` setting). In v5, it should only open when there is an error, which should notify the user. The thinking goes like this: we either have to pop up an error message window or just show the terminal that will have a lot more info and details of the error - we choose the latter. In short, the goal is to make the open-terminal logic smarter and more dynamic, so there is no need to use a static control like `jest.showTerminalOnLaunch`.

Is there an error at the time when the terminal was shown? If not, then there is a bug we should fix (please help us repro).

(Please note that you can always close the terminal after viewing the error)

**Comment by KevinBatdorf** [comment]
You're also assuming that every JavaScript project is using Jest (I'm guessing because it finds the executable?). I have multiple projects that aren't using Jest at all, so I see an error show up again now as of the update. I'm not even sure it's an error, it just loads up in a terminal. 

> found:
>   rootPath: /Users/kevin/code/project
>   jestCommandLine: "/Users/kevin/code/project/node_modules/.bin/jest"
>
> No tests found related to files changed since last commit.
>
> Test run started at 12/21/2022, 1:03:49 PM <
> Test run finished at 12/21/2022, 1:03:49 PM <

I have no Jest tests in this project, and a dependency I need for other reasons is installing Jest. I'm not using it on this project. 

> (Please note that you can always close the terminal after viewing the error)

I'm sure you understand how inconvenient this is to do every time you open a project. I probably open/close multiple projects a day. 

--

Instead of flashing the terminal, could you just colorize the status bar like Prettier does? Or literally any other approach that doesn't force us to act?

![Screen Shot 2022-12-21 at 1 13 08 PM](https://user-images.githubusercontent.com/1478421/208975168-5223547b-f98e-472c-ae70-897d2193dcd2.png)

**Comment by jakemhiller** [comment]
I think with the change that was made to show the terminal when there is an error you've inadvertently ended up in the same situation that led to creating the `showTerminalOnLaunch` flag. The current UX forces me to deal with the failing test and actively gets in the way of any focus I might have had on the task i was doing, especially if I was actively working in the terminal. I agree with @KevinBatdorf that flashing the status bar or some other more subtle way of showing an error by default (or as an option at least) makes a lot of sense here.

**Comment by connectdotz** [comment]
@KevinBatdorf, you raised good points!

> You're also assuming that every JavaScript project is using Jest (I'm guessing because it finds the executable?).

Not every javascript project 😏, but those with a jest in node_modules will indeed activate the extension. I was a bit surprised that a project not using jest could still have jest in the node_module.... Can you give us a bit more detail so we can see if we can improve the activation logic to avoid such false positive. 

In any case, you convinced me that to treat "no test" as an error might not be the proper severity. I will change that to a warning in the next release.

> Instead of flashing the terminal, could you just colorize the status bar like Prettier does? 

I also agree with @jakemhiller that this is a great idea! 😃  With this visual cue, I think we could add a `jest.showTerminalOnError` setting, knowing the alert is not lost.

@jakemhiller Just want to make sure we are on the same page, the errors triggered the show-terminal is not regular test errors but operation or configuration errors that prevented jest from running normally. These should be relatively rate but I do agree we could enhance it as mentioned above.

**Comment by KevinBatdorf** [comment]
> I was a bit surprised that a project not using jest could still have jest in the node_module.... Can you give us a bit more detail so we can see if we can improve the activation logic to avoid such false positive.

In my case it's for a WordPress editor plugin ([link](https://github.com/KevinBatdorf/code-block-pro/)) that uses a WordPress "scripts" package that installs the kitchen sink ([link](https://github.com/WordPress/gutenberg/blob/trunk/packages/scripts/package.json)). Some of the utilities are useful to me but I'm just not using the testing packages they include.

> With this visual cue, I think we could add a jest.showTerminalOnError setting, knowing the alert is not lost.

Does it pop open the terminal whenever a test fails, or whenever a config item fails? If it opens on any test failure then that kinda goes against any TDD workflow anyway where you _expect_ a lot of errors. Losing focus would be really frustrating I imagine. The status bar color highlight I think is a good balance as you get the visual cue but don't need to perform an action.

**Comment by connectdotz** [comment]
@KevinBatdorf I was not able to reproduce a forced terminal open for the project with no tests... No test is not an error, I was wrong to assume that it was. So now I am puzzled why you will see the terminal open... Do you happen to have a multi-root workspace, and some other folders have errors that caused the terminal panel to show up?

> Does it pop open the terminal whenever a test fails, or whenever a config item fails?

not test failure:

> the errors triggered the show-terminal is not regular test errors but operation or configuration errors that prevented jest from running normally. 

i.e. the errors that caused jest process not able to run/start.

**Comment by connectdotz** [comment]
@KevinBatdorf, sorry for going back and forth on this one. It looks like no test is not an error that should force the terminal panel to show if it was hidden. Can you confirm that the terminal panel was hidden when you started vscode, and then it was shown with the terminal output you quoted earlier? I couldn't reproduce it in my sample repo, wondering what did I miss?

**Comment by KevinBatdorf** [comment]
It's no problem. I don't mind helping if I can. It doesn't focus a terminal, but when I open a terminal, it's overtaken by the Jest terminal message:

https://user-images.githubusercontent.com/1478421/209021894-38d56e10-ddd1-4140-909b-001c1b8c28eb.mov

If I had a session open previously, it will open the Jest terminal session in the background.


https://user-images.githubusercontent.com/1478421/209022194-68e61e0c-c156-4244-a67e-c018ffc8e773.mov

In the first video I'm pressing the keyboard shortcut to open the terminal manually. In the second video, it's open because it was open when I closed the editor.

**Comment by KevinBatdorf** [comment]
Another symptom is that the session starts whenever I press save as well. in this video I click the editor to focus it, then press `cmd + s` to save it


https://user-images.githubusercontent.com/1478421/209035627-1a7af2f9-39af-4784-811d-593792419c3f.mov

**Comment by connectdotz** [comment]
Thanks for the video. I think I see what the disconnection is now. Let me see if I can make this more clear:

in v4.6 the terminal is unconditionally open in the "foreground" mode, i.e. it will add the bottom panels to you window if you don't have it yet, and make itself the "active" terminal/panel. This is too intrusive, especially for those who prefer no panel view (like the use case @janaagaard75 mentioned), so we added the `jest.showTerminalOnLaunch` flag.

in v5, we used a "background" terminal by default, i.e. it does not force open the panels if it's hidden, nor making itself the "active" terminal. In other words, the content is hidden unless it is the only or latest terminal; or when user explicitly click on the terminal label to bring it to the "foreground" (a.k.a. the active terminal); or when there is a "fatal" error...

When I say "show terminal", I mean the operation to bring the terminal to the foreground or making it the active terminal. Right now, it only does this when there is "fatal" or execution error (not test error) that could prevent jest from starting. The setting I am considering adding will only control "when" to bring the terminal to foreground, it will not change the fact the terminal will remain to be in the background (you will see it in the terminal list on the right sidebar).

I can understand coming from 4.6, one could easily associate the background terminal with the "foreground" terminal we used to have. This all sounded more complicated than it really is. Please give it a few days and hopefully you can see the difference and find it useful... I did 😄 

On the other hand, it is also possible there are bugs and the system is not working as it should.   Lets examine each of your use case to make sure:

@janaagaard75:
> While I do use VSCode's terminal window, it's not something that keep open, because I prefer having more screen real estate for my code, and to be less distracted.

If jest is running correctly, you should not see terminal window pop up if you have it hidden. Is that not the case in 5.1.0?

@jakemhiller:
> The current UX forces me to deal with the failing test and actively gets in the way of any focus I might have had on the task i was doing, especially if I was actively working in the terminal.

It should not force you to deal with failing tests... or maybe I don't quite understand what you really mean. If you have the jest terminal as your active terminal then yes you will see test output just like running jest on the terminal. If you are working on another terminal, then you should not be seeing the jest terminal output at all, if jest is running correctly... What did I miss?

@KevinBatdorf:

looking further into your use case, it seems it's not a terminal issue, but we activate your workspace that you don't intent to use jest. Even if we can hide terminal, the jest process might still be running in the background, which is not what you want. If it is in a multi-root project, you could exclude the workspace with `jest. disabledWorkspaceFolders`; if it's a single-root, even easier, just use vscode to exclude this extension from the given workspace.

----
Sorry for a very long reply. I don't mind implementing the change we discussed above, but want to make sure I understand the actual root cause, so we don't waste time fixing the wrong issue...

**Comment by KevinBatdorf** [comment]
I need to disable it on lots of projects, I guess. I just opened a PHP project and deeply nested is a Jest executable. This one force opened the terminal.

>[error] Abort jest session: Not able to auto detect a valid jest command: multiple candidates found Perhaps this is a multi-root monorepo?

I'd suggest you assume there is no Jest until you can confirm it 100%, and otherwise allow users to opt in somehow if they need to. But don't make a change just for me, of course. I'm ok disabling it. Just consider this feedback.

**Comment by connectdotz** [comment]
@KevinBatdorf, thanks for sharing your use case and feedback. We definitely want to be precise and eliminate false positives, as much as false negatives... before v5, many users complained that we did not activate their jest a few directories down, so we implemented the deep activation; and now we are seeing the opposite issues. 😢 

Let's see if we can see some patterns to improve the logic. Can you show us the rest of the auto-config output, it should tell the possible jest directories the system found. Would be very helpful if you can also help us understand why those directories are there. 

Every project is different, and we are probably unable to cover every use case. But it's too early to throw in the towel...

**Comment by KevinBatdorf** [comment]
I'll be away for a bit but the project in question was a different PHP project that uses 3rd party code (not necessarily in /vendor) and I remember the output listing about 20 directories (some nested maybe 6-7 levels deep) and mentioning it found multiple executables (maybe).

This project has no Jest tests in the root nor a package.json either.

**Comment by connectdotz** [comment]
@KevinBatdorf, do you mind opening a new issue for this deep-activation related problem, it deserves a separate dedicated thread. 

For other terminal-related issues, let's reconvene in #973.

**Comment by janaagaard75** [comment]
I think @connectdotz’ suggestion of having a `jest.showTerminalOnError` setting is really good.

I can certainly see the value in opening the terminal when a test is failing, but I still think that this setting should default to false. I am concerned that it will become the norm that extensions will open the terminal without requiring user interaction, and that they will just end up competing for my attention.

**Comment by unknownconstant** [comment]
Oh my goodness, I just spent about three hours tracking this down.

I would also very much appreciate a flag to opt into this for specific projects and it not be on by default.

I've got a project with a bunch of different testing libraries, and I make use of vscode's terminals to display code generation & program output. It's a problem that every time I save a file in the project I have to manually switch the terminal back to what I want to see, because jest is detecting an error (which I know about before it does). 

Unless I'm actively debugging tests / using tests it's causing more harm than benefit to my productivity to have focus removed from what I was looking at.

This extension is on the whole really useful, but I can't work out how to prevent this behaviour without disabling the extension

**Comment by connectdotz** [comment]
Hi, this issue has been addressed with a new setting `jest.autoRevealOutput` in [5.2.0 pre-release](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v5.x.md#v520-pre-release); feel free to give it a try and let us know if there is any issue.
