### ISSUE TITLE
Doesn't work when project root is in subdirectory, even with rootPath set

### ISSUE THREAD

**Issue by nikiask** [jest-community/vscode-jest#862]
### Environment

1. `vscode-jest version`: 4.4.0
2. `node -v`: 17.3.0
3. `npm -v` or `yarn --version`: 8.3.0
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): react-scripts 5.0.1
5. your vscode-jest settings if customized:
    - jest.rootPath: "app"
6. Operating system: macOS Monterey 12.3.1

I have a repro of this issue in the following repository https://github.com/nikiask/jestvscodeissue.
There are two folders: app which is a fresh create react app, and .vscode which has a settings.json that only has "jest.rootPath": "app". When opened the extension doesn't recognize any jest tests. However, if you open the app subdirectory in vscode it works perfectly. I thought the rootPath setting was for this, but it has no effect.

**Comment by connectdotz** [comment]
Hi, it seems that vscode did not activate the extension because of no qualified [activation event](https://github.com/jest-community/vscode-jest/blob/8abe1b0f94b5a564599019182ae48a89dcfa6a1d/package.json#L33) in your top-level folder.

You can still manually activate the extension by running `Jest: Run All Tests` from the command palette; or open vscode from the `app` folder, as you already discovered.

**Comment by nikiask** [comment]
Ah thanks for the info. I added a vscode task to start the jest extension when my project is opened.

For others, add this to .vscode/tasks.json to run jest when opening your project:
```json
    {
      "label": "start jest on open",
      "command": "${command:io.orta.jest.start}",
      "runOptions": {
        "runOn": "folderOpen"
      }
    }
```

Would it make sense to change some activation events to use globs if anyone else has this issue? Such as "workspaceContains:node_modules/.bin/jest" -> "workspaceContains:**/node_modules/.bin/jest". I can submit a pull request if you want.
