### ISSUE TITLE
Jest error on opening non-Jest workspace root

### ISSUE THREAD

**Issue by insysion** [jest-community/vscode-jest#877]
On opening a workspace with multiple roots, one of them (my `.github` folder, as it happens) fails with the following error. 

```
not-test-5 is scheduled
Jest Session Started
not-test onProcessExit: process exit with code=127, signal=undefined
```
Interestingly, this doesn't happen if I open the folder individually.

There's only one YAML file in there. What's happening here? Why is Jest running in there at all? How can I stop this happening?

**Comment by connectdotz** [comment]
@insysion is this resolved?

**Comment by raxetul** [comment]
> Try 'jest.disabledWorkspaceFolders'

Deciding to activate jest plugin according to jest option existence instead of checking "exceptional case option in jest settings" would be more convenient. Obviously other VS Code workspace will not include jest option.

**Comment by connectdotz** [comment]
@raxetul agree. Better detection for the monorepo projects has been on our wish list for some time. For now, users can use the setting to exclude the folders explicitly.

**Comment by connectdotz** [comment]
After investigating further, turns out it's not easy to determine if a workspace is jest workspace or not. Even if the folder has no jest node_modules, it still could be using a globally installed "jest". 

I am thinking if we can't reliably predetermine the eligibility, maybe we can add a "exclude" button in the error panel for monorepo projects, so users can easily exclude the workspace, if applicable, without manually editing the settings. 

What do you guys think?

**Comment by raxetul** [comment]
Extension users might be enforced to use jest configuration as the jest configuration file or package.json internal configuration. If there is an existence of one of them, extension may activate itself.

**Comment by segevfiner** [comment]
Can't the extension just anchor itself on the existence of a jest config file somewhere under each workspace folder to figure out if it has jest tests it should try to detect?

**Comment by connectdotz** [comment]
we could, but when a folder lacks the jest config, we can't 100% exclude it since it might still use config from another folder. Therefore, instead of deploying all kinds of complex logic, we decided to settle on the simplest approach, at least for now until we have better deterministic logic, while allowing users to simply and explicitly turn off the ones they don't want.

**Comment by connectdotz** [comment]
anyway, this is the current behavior, we can further discuss enhancement approach in maybe a discussion. Close the issue.

**Comment by insysion** [comment]
> @insysion is this resolved?

Apologies for the late reply. Yes, this is resolved.
