### ISSUE TITLE
Clicking on debug codelens throws MODULE_NOT_FOUND error (used with Yarn v3)

### ISSUE THREAD

**Issue by geekox86** [jest-community/vscode-jest#893]
### Environment

1. `vscode-jest version`: v4.6.0
2. `node -v`: v18.7.0
3. `yarn --version`: 3.2.2
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 28.1.3
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? yarn jest
    - jest.autoRun? [Not customized]
    - anything else that you think might be relevant? I am using Yarn v3 which does not have node_modules folder assumed by vscode-jest debug codelens.
6. Operating system: macOS Big Sur v11.6.5

### Prerequisite
- are you able to run jest test from the command line? Yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) yarn test

### Steps to Reproduce

[[Repo link]](https://github.com/geekox86/xstate-cache)

### Relevant Debug Info

```
/usr/bin/env 'NODE_OPTIONS=--require "/Applications/Visual Studio
 Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js"
 --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/var/folders/w1/r8twtpm11f5
0gdmy4g3x464w0000gn/T/node-cdp.57669-47.sock","deferredMode":false,"waitForDebugger":"","execPath":
"/usr/local/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/var/folders
/w1/r8twtpm11f50gdmy4g3x464w0000gn/T/node-debug-callback-f11ddb29b1a8f91e"}' /usr/local/bin/node ./
node_modules/.bin/jest --runInBand --watchAll=false --testNamePattern starts\ at\ request\\.idle\ a
nd\ response\\.none\ states --runTestsByPath /Users/geekox86/Documents/Projects/xstate-cache/src/Qu
ery.test.ts 
Debugger attached.
Waiting for the debugger to disconnect...
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '/Users/geekox86/Documents/Projects/xstate-cache/node_modules/.bin/jest'
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.7.0
```

### Expected Behavior

vscode-jest should respect the jest.jestCommandLine configuration when clicking on debug codelens.

### Actual Behavior

vscode-jest does not respect the jest.jestCommandLine configuration when clicking on debug codelens.
Instead, it assumes `/usr/local/bin/node ./node_modules/.bin/jest`.
I am using Yarn v3 which does not have node_modules folder.

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
@geekox86 you can use the "setup wizard" to create the debug config with the jest.jestCommandLine setting. Please see [Setup Wizard](https://github.com/jest-community/vscode-jest/blob/master/setup-wizard.md) for details.

**Comment by westonNexben** [comment]
This didn't work for me.  Still get:

```
Error: Cannot find module '/usr/src/app/node_modules/.bin/jest'
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I think "Debug" ignores the "Jest Command Line" setting somehow.

**Comment by connectdotz** [comment]
after updating the jest.jestCommandLine, you would need to use the wizard to generate a new debug config so it could pick up your new command line.

**Comment by westonNexben** [comment]
That's what I did, but the "launch.json" `cwd` path was wrong; it repeated the `rootPath` twice.  Even after manually fixing the "launch.json", it still ran `'/usr/src/app/node_modules/.bin/jest'`, which is the root directory of the monorepo, not my subdirectory in my "multi root" workspace.

**Comment by connectdotz** [comment]
hmm... can you share your debug config and `jest.jestCommandLine`, `jest.rootPath` setting so I can take a closer look.

**Comment by westonNexben** [comment]
I finally got it to work, but there were some strange things:

1. I disabled autorun right away because that adds too many potential complications
1. Starting with a multi root Workspace, I'm not sure how VS Code chooses which root folder to scan to automatically activate "vscode-jest".  But it didn't choose the right one because it didn't activate.
1. I had to configure `rootPath` temporarily at the Workspace level, relative to the monorepo root but pointing to my subdirectory, to get the extension to activate normally and automatically
1. Then I was able to run "Jest: Setup Extension (Beta)", this time actually for my root subdirectory
1. The debug "launch.json" configuration generates incorrectly in my case because `program` needs the absolute path to the executable, and in a monorepo, a manager like RushJS's `rushx` is installed globally as opposed to per-project.  `${workspaceFolder}/rushx`, analogous to `npx`, is incorrect.  So I adjusted that manually.

In contrast, the Jest Runner extension doesn't require multi root or anything special to work; just open a test file and Run | Debug are visible in CodeLens.  It must walk the parent directories to find the nearest `jest`.  It just works with zero configuration: https://marketplace.visualstudio.com/items?itemName=firsttris.vscode-jest-runner

**Comment by connectdotz** [comment]
@westonNexben, thanks for digging, and I'm glad you get it working. 👍 

Your point is taken. I agree we should be able to do better for deterministic situations such as single root with deeper activation point (jest config in a subdirectory). I am working on improving the default command detection, will ping you when it's ready for testing.

**Comment by connectdotz** [comment]
@westonNexben [v5.0.3](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v5.md) is out, would love to have you try it out and let me know your experience.

**Comment by westonNexben** [comment]
Awesome, thank you @connectdotz !  I'll find some time to give it a try.

**Comment by molt2020** [comment]
I am not sure if this issue is fully closed, I don't have a Monorepo but still struggling to get individual test debug button to work in VS Code with Jest extension. Similar to the above, I use set-up wizard to create debug configuraiton and there I enter my npx location as absolute path which works; however when I click the debug icon against individual test I get below error. I can run all tests without problem and I can get debugging for individual tests working using JestRunner, but not with the Jest Extension.

```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

JestRunner extension is running fine but I would prefer that Jest extension works as expected...
