### ISSUE TITLE
Can't run it with ES Module

### ISSUE THREAD

**Issue by yi-ge** [jest-community/vscode-jest#903]
### Environment

1. `vscode-jest version`: [v4.6.0]
2. `node -v`: [v18.8.0]
3. `npm -v` or `yarn --version`: [1.22.18]
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): [jest@28.1.2]
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? [npm run test:jest --  ]
    - jest.autoRun? [no]
    - anything else that you think might be relevant? [reporters option]
6. Operating system: [MacOS]

### Prerequisite
- are you able to run jest test from the command line? [no]
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) 

```bash
node --no-warnings --experimental-vm-modules --experimental-specifier-resolution=node node_modules/jest/bin/jest.js --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_arithmetic_practice_2.json --no-coverage --reporters default --reporters /home/yige/.vscode/extensions/orta.vscode-jest-4.6.0/out/reporter.js --colors --watchAll=false --testPathPattern /home/yige/Project/arithmetic-practice/test/array/01-matrix\.test\.ts
```

### Steps to Reproduce

Run:
```bash
node --no-warnings --experimental-vm-modules --experimental-specifier-resolution=node node_modules/jest/bin/jest.js --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_arithmetic_practice_2.json --no-coverage --reporters default --reporters /home/yige/.vscode/extensions/orta.vscode-jest-4.6.0/out/reporter.js --colors --watchAll=false --testPathPattern /home/yige/Project/arithmetic-practice/test/array/01-matrix\.test\.ts
```

with `package.json`: `"type": "module",`.

### Relevant Debug Info

`ReferenceError: exports is not defined`

![image](https://user-images.githubusercontent.com/6657330/188602684-83507a5b-b280-46f2-a12b-3d048d1b4c62.png)

About Code:

https://github.com/jest-community/jest-editor-support/blob/b014846c30258cbf8a5b28244d2dc15fa63fe18d/src/Runner.js#L81-L85

https://github.com/jest-community/vscode-jest/blob/master/src/reporter.ts

https://github.com/jest-community/vscode-jest/blob/1fec32a6e9caf997c4dc344fd96b1a2e8615ece3/src/JestProcessManagement/JestProcess.ts#L98-L109

Since `module.exports` is used in the `reporter.js` file, this plugin cannot be used normally in the ES Module environment.

**Comment by yi-ge** [comment]
The `exports is not defined` error resulting in to the `--testLocation Results` option.

**Comment by yi-ge** [comment]
`jest` v29.0.2 fix the bug. close this issues.

**Comment by Kampfmoehre** [comment]
Sorry to answer to an old issue, but I still have this bug, trying to convert a package to ESM. I got the tests working on the terminal with
`NODE_OPTIONS=--experimental-vm-modules npx jest`

I have enabled the `debugMode` in settings but can not see any logs. The only line I get from Jest output is 
`<project> warning | success 0, fail 4, unknown 0; mode: auto-run-watch; state: idle`

Clicking on `Reveal test output` in test explorer I can see `ReferenceError: exports is not defined` logged for each test but also the node experimental warning for VM modules.

I have set the `jestCommandLine` to `NODE_OPTIONS=--experimental-vm-modules npx jest --coverage` since setting nodeEnv does not seem to work for me
```json
{
  "jest.nodeEnv": {
    "NODE_OPTIONS": "--experimental-vm-modules"
  },
  "jest.jestCommandLine": "NODE_OPTIONS=--experimental-vm-modules npx jest --coverage",
  "jest.debugMode": true
}
```

I am using jest 29.4.2 (confirmed with `npm ls jest`).

Is there anything I can do to make tests work again, I really like this extension?

**Comment by connectdotz** [comment]
@Kampfmoehre please see [How to see more debug info](https://github.com/jest-community/vscode-jest#how-to-see-more-debug-info-self-diagnosis) to find the actual command the extension emitted. You should see something like this:
```
[Extension Host] spawning process with command=yarn test --testLocationInResults --json --useStderr --outputFile /var/folders/vg/yw9mltwd1mj_29xbvhwywc980000gn/T/jest_runner_vscode_jest_501.json --watch --no-coverage --reporters default --reporters "/Users/vsun/.vscode/extensions/orta.vscode-jest-5.2.3/out/reporter.js" --colors options: Object
```

Can you try the following: changing the `reporter.js` to `reporter.cjs`, from the directory where it says `--reporters "/Users/vsun/.vscode/extensions/orta.vscode-jest-5.2.3/out/reporter.js"` then run the command (with the replaced cjs instead) in the terminal to see if that works. I hope this will give nodejs enough hint that the reporter is a commonjs module. Let me know what you find so we can see how to address this issue properly.

**Comment by Kampfmoehre** [comment]
@connectdotz Thx for the hint about debugging. In the developer console I can see, that it at least uses the Node Options I provided:
```bash
NODE_OPTIONS=--experimental-vm-modules npx jest --testLocationInResults --coverage --listTests --json --watchAll=false

NODE_OPTIONS=--experimental-vm-modules npx jest --testLocationInResults --coverage --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_<project>_1000.json --watch --no-coverage --reporters default --reporters "/home/<user>/.vscode/extensions/orta.vscode-jest-5.2.3/out/reporter.js" --colors
```
The first one is correctly detecting my test files, the second one starts jest in watch mode but doesn't run any test. Jest says there are no tests changed since last commit. I can make small changes in every test file then it actually runs those plus I can see in the test explorer that they turn from red to green.

When I add replace the extension of the reporters path with cjs I get an error instead
```
Error: Could not resolve a module for a custom reporter.
  Module name: /home/<user>/.vscode/extensions/orta.vscode-jest-5.2.3/out/reporter.cjs
    at /home/<user>/dev/<project>/node_modules/jest-config/build/normalize.js:426:15
    at Array.map (<anonymous>)
    at normalizeReporters (/home/<user>/dev/<project>/node_modules/jest-config/build/normalize.js:409:20)
    at /home/<user>/dev/<project>/node_modules/jest-config/build/normalize.js:747:17
    at Array.reduce (<anonymous>)
    at normalize (/home/<user>/dev/<project>/node_modules/jest-config/build/normalize.js:608:14)
    at async readConfig (/home/<user>/dev/<project>/node_modules/jest-config/build/index.js:160:45)
    at async readConfigs (/home/<user>/dev/<project>/node_modules/jest-config/build/index.js:417:26)
    at async runCLI (/home/<user>/dev/<project>/node_modules/@jest/core/build/cli/index.js:152:59)
    at async Object.run (/home/<user>/dev/<project>/node_modules/jest-cli/build/run.js:124:37)
```
But thx anyway it seems to work now and I will keep an I eye on it. I am not 100% sure but running the command manually and making small changes to each test seems to have permanently fixed the problem. Even after reverting alle changes and restart VS Code the tests will now run directly at start (though the test explorer states "outdated result" when hovering above the test).
